// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://igsqqvaghjjmvxwfhgce.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlnc3FxdmFnaGpqbXZ4d2ZoZ2NlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ1NjM5MTAsImV4cCI6MjA2MDEzOTkxMH0.0z1tIc9sl3e_W6weV1BaGKloeILQGODGhwtGBD-0voQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);